from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

from .script_generator import ManimScriptGenerator


QUALITY_FLAGS = {
    "l": "-ql",
    "m": "-qm",
    "h": "-qh",
    "p": "-qp",
    "k": "-qk",
}


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate/render a Manim script from ScenePlan JSON.")
    parser.add_argument("scene_plan", help="ScenePlan JSON generated by visual.pipeline")
    parser.add_argument("--script", default="generated_explanation.py", help="Generated .py path")
    parser.add_argument("--render", action="store_true", help="Invoke Manim after generating the script")
    parser.add_argument("--quality", choices=sorted(QUALITY_FLAGS), default="l")
    parser.add_argument("--media-dir", default="media")
    args = parser.parse_args()

    scene_path = Path(args.scene_plan).expanduser().resolve()
    payload = json.loads(scene_path.read_text(encoding="utf-8"))
    script = ManimScriptGenerator().generate(payload, args.script)
    print(f"Generated Manim script: {script}")

    if not args.render:
        return

    cmd = [
        sys.executable,
        "-m",
        "manim",
        QUALITY_FLAGS[args.quality],
        "--media_dir",
        str(Path(args.media_dir).expanduser().resolve()),
        str(script),
        "GeneratedExplanation",
    ]
    print("Running:", " ".join(cmd))
    completed = subprocess.run(cmd, check=False)
    raise SystemExit(completed.returncode)


if __name__ == "__main__":
    main()
