from __future__ import annotations

import json
from dataclasses import asdict, is_dataclass
from pathlib import Path
from typing import Any


class ManimScriptGenerator:
    """Generate a standalone Manim scene from a serialized ScenePlan.

    The generated file intentionally contains only generic visual primitives.
    Visual semantics have already been decided upstream by VisualBinder and
    ScenePlanner. This keeps Manim as a rendering backend rather than a second
    explanation planner.
    """

    def generate(self, scene_plan: Any, output_path: str | Path) -> Path:
        output = Path(output_path).expanduser().resolve()
        output.parent.mkdir(parents=True, exist_ok=True)
        payload = asdict(scene_plan) if is_dataclass(scene_plan) else scene_plan
        json_payload = json.dumps(payload, ensure_ascii=False)
        output.write_text(self._template(json_payload), encoding="utf-8")
        return output

    @staticmethod
    def _template(json_payload: str) -> str:
        # Keep the generated script self-contained so it can be executed with
        # `python -m manim generated_scene.py GeneratedExplanation`.
        payload_literal = repr(json_payload)
        return f'''# Auto-generated by computer_core_mvp/manim_backend.
# Do not hand-edit if you want reproducible output; regenerate from ScenePlan.
from __future__ import annotations

import json
import math

from manim import *

SCENE_PLAN = json.loads({payload_literal})


RELATION_LABELS = {{
    "CONTAINS": "包含",
    "PART_OF": "属于",
    "IS_A": "是一种",
    "HAS_SUBTYPE": "包含类别",
    "USES": "使用",
    "USED_BY": "被使用",
    "EXECUTES": "执行",
    "EXECUTED_BY": "由其执行",
    "CONTROLS": "控制",
    "CONTROLLED_BY": "受控制",
    "MANAGES": "管理",
    "MANAGED_BY": "受管理",
    "STORES": "存储",
    "STORED_IN": "存于",
    "TRANSFORMS_TO": "转换为",
    "TRANSFORMED_FROM": "由其转换",
    "INTERFACES_WITH": "接口",
    "IMPLEMENTS": "实现",
    "IMPLEMENTED_BY": "由其实现",
    "AFFECTS": "影响",
    "AFFECTED_BY": "受影响",
    "EXPLOITS": "利用",
    "EXPLOITED_BY": "被利用",
    "CONTRASTS_WITH": "对比",
    "DESCRIBES": "描述",
    "CONSTRAINS": "约束",
    "CONNECTS": "连接",
    "CONNECTED_BY": "相连",
}}


def _font_size(name: str) -> int:
    n = len(name)
    if n <= 8:
        return 28
    if n <= 16:
        return 24
    return 20


def _label(text: str, size: int | None = None):
    return Text(text, font_size=size or _font_size(text))


def _box_with_label(name: str, width=2.6, height=1.25, radius=0.16):
    box = RoundedRectangle(width=width, height=height, corner_radius=radius)
    label = _label(name)
    if label.width > width * 0.82:
        label.scale_to_fit_width(width * 0.82)
    if label.height > height * 0.7:
        label.scale_to_fit_height(height * 0.7)
    return VGroup(box, label)


def make_node(spec: dict):
    archetype = spec.get("archetype", "functional_block")
    name = spec.get("name", spec.get("knowledge_node_id", "?"))

    if archetype == "code_block":
        box = RoundedRectangle(width=3.1, height=1.55, corner_radius=0.12)
        title = _label(name, 24).move_to(box.get_top() + DOWN * 0.35)
        lines = VGroup(*[
            Line(LEFT * 0.8, RIGHT * (0.7 - i * 0.07), stroke_width=2)
            for i in range(3)
        ]).arrange(DOWN, buff=0.16).move_to(box.get_center() + DOWN * 0.25)
        obj = VGroup(box, title, lines)
    elif archetype == "bit_field":
        cells = VGroup(*[Rectangle(width=0.55, height=0.62) for _ in range(5)]).arrange(RIGHT, buff=0)
        bits = VGroup(*[Text(ch, font_size=22).move_to(c) for ch, c in zip("10110", cells)])
        title = _label(name, 22).next_to(cells, UP, buff=0.16)
        obj = VGroup(cells, bits, title)
    elif archetype == "bit_cell":
        cell = Square(side_length=0.9)
        bit = Text("0/1", font_size=22).move_to(cell)
        title = _label(name, 20).next_to(cell, DOWN, buff=0.12)
        obj = VGroup(cell, bit, title)
    elif archetype == "storage_block":
        box = RoundedRectangle(width=2.8, height=1.7, corner_radius=0.1)
        grid = VGroup()
        for x in (-0.7, 0, 0.7):
            grid.add(Line(UP * 0.35, DOWN * 0.35).shift(RIGHT * x))
        for y in (-0.35, 0.35):
            grid.add(Line(LEFT * 1.05, RIGHT * 1.05).shift(UP * y))
        grid.move_to(box.get_center() + DOWN * 0.15)
        title = _label(name, 23).move_to(box.get_top() + DOWN * 0.27)
        obj = VGroup(box, grid, title)
    elif archetype == "interface_layer":
        box = RoundedRectangle(width=4.0, height=1.0, corner_radius=0.14)
        title = _label(name, 26).move_to(box)
        obj = VGroup(box, title)
    elif archetype == "interface_hub":
        body = Circle(radius=0.8)
        title = _label(name, 22).move_to(body)
        ports = VGroup(*[
            Line(ORIGIN, RIGHT * 0.7).rotate(a).shift(body.get_center())
            for a in (0, PI/2, PI, -PI/2)
        ])
        obj = VGroup(body, ports, title)
    elif archetype == "data_token":
        box = RoundedRectangle(width=2.2, height=0.8, corner_radius=0.35)
        obj = VGroup(box, _label(name, 22).move_to(box))
    elif archetype == "hardware_icon":
        body = Square(side_length=1.65)
        pins = VGroup()
        for d in (-0.55, 0, 0.55):
            pins.add(Line(LEFT * 1.05, LEFT * 0.82).shift(UP * d))
            pins.add(Line(RIGHT * 0.82, RIGHT * 1.05).shift(UP * d))
        obj = VGroup(body, pins, _label(name, 22).move_to(body))
    elif archetype == "transformer":
        box = RoundedRectangle(width=2.5, height=1.2, corner_radius=0.2)
        arrow = Text("⇢", font_size=28).move_to(box.get_center() + DOWN * 0.15)
        title = _label(name, 22).move_to(box.get_top() + DOWN * 0.27)
        obj = VGroup(box, title, arrow)
    elif archetype == "category_group":
        box = DashedVMobject(RoundedRectangle(width=3.0, height=1.5, corner_radius=0.18))
        obj = VGroup(box, _label(name, 24).move_to(box))
    elif archetype in {{"container", "hierarchy", "functional_diagram", "physical_system", "concept_layer"}}:
        obj = _box_with_label(name, width=3.0, height=1.45)
    elif archetype in {{"metric", "timeline", "parallel_flow", "pipeline", "network", "access_pattern", "process_flow", "primitive_symbol", "memory_chip", "external_device"}}:
        obj = _box_with_label(name, width=2.65, height=1.15)
    else:
        obj = _box_with_label(name)

    obj.scale(float(spec.get("scale", 1.0)))
    obj.move_to([float(spec.get("x", 0)), float(spec.get("y", 0)), 0])
    return obj


def make_relation(rel: dict, objects_by_node: dict):
    src_id = rel.get("source_node_id")
    dst_id = rel.get("target_node_id")
    if src_id not in objects_by_node or dst_id not in objects_by_node:
        return None
    src = objects_by_node[src_id]
    dst = objects_by_node[dst_id]
    arrow = Arrow(src.get_center(), dst.get_center(), buff=0.65, stroke_width=2.4, max_tip_length_to_length_ratio=0.12)
    raw = rel.get("label", "")
    text = RELATION_LABELS.get(raw, raw)
    label = Text(text, font_size=18)
    label.next_to(arrow.get_center(), UP, buff=0.08)
    return VGroup(arrow, label)


def flash_relation(scene: Scene, rel_obj, pattern_id: str):
    if rel_obj is None:
        return
    if pattern_id in {{"CONTROL_SIGNAL", "RESOURCE_FLOW", "TOKEN_ENTER_AND_ACT", "PIPELINE_TRANSFORM", "PROCESS_FLOW"}}:
        scene.play(Create(rel_obj[0]), FadeIn(rel_obj[1]), run_time=0.8)
        scene.play(Indicate(rel_obj[0]), run_time=0.45)
    elif pattern_id in {{"INTERFACE_BRIDGE", "ABSTRACT_TO_CONCRETE", "OVERLAY"}}:
        scene.play(Create(rel_obj[0]), FadeIn(rel_obj[1]), run_time=0.8)
    else:
        scene.play(Create(rel_obj[0]), FadeIn(rel_obj[1]), run_time=0.65)


class GeneratedExplanation(Scene):
    def construct(self):
        plan = SCENE_PLAN
        title = Text(plan.get("question", "Explanation"), font_size=28).to_edge(UP)
        self.play(FadeIn(title), run_time=0.5)
        self.wait(0.2)

        objects_by_node = {{}}
        relation_objects = []

        for index, scene_spec in enumerate(plan.get("scenes", [])):
            scene_title_text = scene_spec.get("title", "")
            scene_title = Text(scene_title_text, font_size=22).to_edge(DOWN)

            desired_ids = {{n.get("knowledge_node_id") for n in scene_spec.get("nodes", [])}}
            carry_ids = set(scene_spec.get("carry_over_node_ids", []))

            # Fade out stale relations before re-layout.
            if relation_objects:
                self.play(*[FadeOut(x) for x in relation_objects], run_time=0.3)
                relation_objects = []

            stale = [nid for nid in list(objects_by_node) if nid not in desired_ids and nid not in carry_ids]
            if stale:
                self.play(*[FadeOut(objects_by_node[nid]) for nid in stale], run_time=0.35)
                for nid in stale:
                    objects_by_node.pop(nid, None)

            # Reuse common knowledge objects across scenes. If the requested
            # profile changes, transform the old object into the new profile.
            motions = []
            reveals = []
            for node_spec in scene_spec.get("nodes", []):
                nid = node_spec.get("knowledge_node_id")
                desired = make_node(node_spec)
                if nid in objects_by_node:
                    old = objects_by_node[nid]
                    motions.append(Transform(old, desired))
                else:
                    objects_by_node[nid] = desired
                    reveals.append(FadeIn(desired))
            if motions:
                self.play(*motions, run_time=0.65)
            if reveals:
                self.play(*reveals, run_time=0.65)

            if index == 0:
                self.play(FadeIn(scene_title), run_time=0.35)
            else:
                self.play(Transform(title, Text(plan.get("question", "Explanation"), font_size=28).to_edge(UP)), run_time=0.01)
                self.play(FadeIn(scene_title), run_time=0.3)

            # Relations are regenerated after node motion so arrows land on the
            # current coordinates.
            rel_map = {{}}
            for rel in scene_spec.get("relations", []):
                obj = make_relation(rel, objects_by_node)
                if obj is not None:
                    rel_map[rel.get("relation_id", str(len(rel_map)))] = {{"obj": obj, "spec": rel}}

            for action in scene_spec.get("actions", []):
                kind = action.get("action_type", "")
                pattern = action.get("pattern_id", "")
                targets = action.get("target_ids", [])
                if kind in {{"focus_node", "definition_focus", "highlight_existing"}}:
                    anims = []
                    for target in targets:
                        nid = target.split(":")[-1] if ":" in target else target
                        if nid in objects_by_node:
                            anims.append(Indicate(objects_by_node[nid]))
                    if anims:
                        self.play(*anims, run_time=float(action.get("duration", 0.7)))
                elif kind in {{"branch_reveal", "support_reveal", "overview_reveal", "reveal_nodes", "split_screen"}}:
                    # Nodes have already been placed; a subtle indication keeps
                    # action semantics without double-creating mobjects.
                    anims = []
                    for target in targets:
                        nid = target.split(":")[-1] if ":" in target else target
                        if nid in objects_by_node:
                            anims.append(Indicate(objects_by_node[nid], scale_factor=1.04))
                    if anims:
                        self.play(*anims, run_time=min(1.0, float(action.get("duration", 0.8))))
                elif kind == "animate_relation":
                    target_set = set(targets)
                    for rel_id, bundle in rel_map.items():
                        rel_obj = bundle["obj"]
                        rel_spec = bundle["spec"]
                        endpoints = {{rel_spec.get("source_visual_id"), rel_spec.get("target_visual_id")}}
                        if target_set and not endpoints.issubset(target_set):
                            continue
                        if rel_obj not in relation_objects:
                            relation_objects.append(rel_obj)
                            flash_relation(self, rel_obj, pattern or rel_spec.get("pattern_id", ""))
                elif kind == "show_note":
                    note = Text(scene_spec.get("narration_hint", "Evidence unavailable"), font_size=24)
                    self.play(FadeIn(note), run_time=0.5)
                    self.wait(0.6)
                    self.play(FadeOut(note), run_time=0.3)

            # Ensure any relation not covered by an explicit relation action is
            # still visible in the final state of the scene.
            remaining = [bundle["obj"] for bundle in rel_map.values() if bundle["obj"] not in relation_objects]
            if remaining:
                self.play(*[Create(obj[0]) for obj in remaining], *[FadeIn(obj[1]) for obj in remaining], run_time=0.6)
                relation_objects.extend(remaining)

            self.wait(0.6)
            self.play(FadeOut(scene_title), run_time=0.2)

        self.wait(0.5)
'''
